### ISSUE TITLE
Smaller or No Page Icons and Less Space at the Top of the Page

### ISSUE THREAD

**Issue by axegirll** [notion-enhancer/notion-enhancer#210]
Problem: 
Icons are aesthetically important because they replace the generic page icon in the sidebar. But when you open the page the icons are huge and take up alot of space. 
![image](https://user-images.githubusercontent.com/73877994/98200640-00dce300-1efc-11eb-9bb2-c901fd8aa3a1.png)

Solution:
It would be nice to have the option for the pages to look more like databases with the small icon to the side but without that useless space at the top:
![image](https://user-images.githubusercontent.com/73877994/98201599-063b2d00-1efe-11eb-9357-70fc67830e84.png)

Alternative:
Another option would be to just size the icon down and remove the space above the icon to something more manageable or be able to hide the icon all together (from the page, not the sidebar).
![image](https://user-images.githubusercontent.com/73877994/98201194-1e5e7c80-1efd-11eb-8150-b99b07c8c3cf.png)

**Comment by CloudHill** [comment]
This css code should make the icons smaller, add it using the custom inserts extension.
```css
/* Place icon relative to the title container */
.notion-scroller[style*="display: flex; flex-direction: column"] > :first-child:not([style*="sticky"]) > :last-child {
    position: relative;
}

/* Set icon size */
.notion-scroller[style*="display: flex; flex-direction: column"] > :first-child:not([style*="sticky"]) .notion-record-icon {
    width: 38px !important;
    height: 38px !important;
}
.notion-scroller[style*="display: flex; flex-direction: column"] > :first-child:not([style*="sticky"]) .notion-record-icon * {
    width: 100% !important;
    height: 100% !important;
}

/* Icon placement */
.notion-scroller[style*="display: flex; flex-direction: column"] > :first-child:not([style*="sticky"]) .notion-record-icon {
    position: absolute !important;
    margin: 0 !important;
    top: 45px;
}

/* Emoji icon */
.notion-scroller[style*="display: flex; flex-direction: column"] > :first-child:not([style*="sticky"]) .notion-record-icon [style*="font-size: 78px"] {
    font-size: 38px !important;
}

/* Push page title to the right */
.notion-record-icon + .notion-page-controls + .notion-page-block {
    margin-left: 52px;
}

/* Remove space on top of the page when no icon or cover is set  */
.notion-page-controls[style*="margin-top: 80px"] {
    margin-top: 8px !important;
}
```
![image](https://user-images.githubusercontent.com/54142180/98446356-8efcd780-214f-11eb-9fd6-cf3a5c5c20fb.png)
