### ISSUE TITLE
Notion coding block

### ISSUE THREAD

**Issue by kerningium** [notion-enhancer/notion-enhancer#221]
The default code block isn't that good. There is no *row numbering* and, there aren't many color variations also for classes, functions, and variables. That makes code a lot messy sometimes.

Consider this example it looks so elegant the *frame* helps it look different from other elements. If possible, a copy icon on the code block to copy the code will save a lot of time.
![Code Block](https://user-images.githubusercontent.com/73218471/98431793-8ddf9200-20de-11eb-863e-058da369d4e2.png)

![Copy Code](https://user-images.githubusercontent.com/73218471/98431812-c2ebe480-20de-11eb-8bba-37a6cf8b93fc.png)

**Comment by CloudHill** [comment]
If you hover over the top right of a code block, there is already a copy button.
![image](https://user-images.githubusercontent.com/54142180/98444063-31ae5980-2142-11eb-82b3-65166cd25f65.png)

**Comment by kerningium** [comment]
> If you hover over the top right of a code block, there is already a copy button.
> ![image](https://user-images.githubusercontent.com/54142180/98444063-31ae5980-2142-11eb-82b3-65166cd25f65.png)

Oh! I never really noticed, thanks

**Comment by CloudHill** [comment]
This piece of css code adds those buttons to code blocks, add it using the custom inserts mod.
```css
.notion-code-block.line-numbers {
  position: relative;
}
.notion-code-block.line-numbers:before {
  content: "•••";
  color: transparent;
  background-image: linear-gradient(
    90deg,
    #FF5F56, #FF5F56 33%,
    #FFBD2E 33%, #FFBD2E 66%,
    #27C93F 66%, #27C93F
  );
  background-clip: text;
  -webkit-background-clip: text;
  font-size: 36px;
  line-height: 0.5;
  position: absolute;
  top: 10px;
  left: 10px;
}
.notion-code-block.line-numbers > div {
  padding-top: 44px !important;
  padding-bottom: 20px !important;
}
```
![image](https://user-images.githubusercontent.com/54142180/98446308-4e9d5980-214f-11eb-9808-3ae35fd9d533.png)
