### ISSUE TITLE
new function

### ISSUE THREAD

**Issue by hzb666** [notion-enhancer/notion-enhancer#446]
Add a function to make the cursor in the center of the screen instead of the bottom of the screen, just like in vscode.

**Comment by dragonwocky** [comment]
add a css custom insert with
```css
.notion-page-content {
  padding-bottom: 50vh !important;
}
```
