### ISSUE TITLE
Tweak 'Smaller page icon' need to  be update （And I suggest a solution）

### ISSUE THREAD

**Issue by l782993610** [notion-enhancer/notion-enhancer#570]
On Notion version 2.11.23.10.2.0, the HTML struct of page has change, which leads to the css selector of Tweak 'Smaller page icon' fail.

**Comment by l782993610** [comment]
The solution above might be usefull. However, when there is not icon at all, the place of is blank.
So I write a better version. Hope it helps.
```css
/* Smaller page icons */

/* Place icon relative to the title container */
.notion-scroller[style*="display: flex; flex-direction: column"] > :first-child:not([style*="sticky"]) > :last-child {
    position: relative;
}

/* Set icon size */
.notion-scroller[style*="display: flex; flex-direction: column"] > :first-child:not([style*="sticky"]) .notion-record-icon {
    width: 38px !important;
    height: 38px !important;
}
.notion-scroller[style*="display: flex; flex-direction: column"] > :first-child:not([style*="sticky"]) .notion-record-icon * {
    width: 100% !important;
    height: 100% !important;
}

/* Icon placement */
.notion-scroller[style*="display: flex; flex-direction: column"] > :first-child:not([style*="sticky"]) .notion-record-icon {
    margin-top: 8px !important;
    margin-right: 8px !important;
    float: left;
}

.notion-scroller[style*="display: flex; flex-direction: column"] > :first-child:not([style*="sticky"]) .notion-page-controls {
  float: right;
  margin-right: 20px;
}

/* Emoji icon */
.notion-scroller[style*="display: flex; flex-direction: column"] > :first-child:not([style*="sticky"]) .notion-record-icon [style*="font-size: 78px"] {
    font-size: 38px !important;
}


/* Remove space on top of the page when no icon or cover is set  */
.notion-page-controls[style*="margin-top: 80px"] {
    margin-top: 8px !important;
}
```

**Comment by l782993610** [comment]
a better version
```css
/* Smaller page icons */

/* Place icon relative to the title container */
.notion-scroller[style*="display: flex; flex-direction: column"] > :first-child:not([style*="sticky"]) > :last-child {
    padding-top: 30px;
    position: relative;
}

/* Set icon size */
.notion-scroller[style*="display: flex; flex-direction: column"] > :first-child:not([style*="sticky"]) .notion-record-icon {
    width: 38px !important;
    height: 38px !important;
}
.notion-scroller[style*="display: flex; flex-direction: column"] > :first-child:not([style*="sticky"]) .notion-record-icon * {
    width: 100% !important;
    height: 100% !important;
}

/* Icon placement */
.notion-scroller[style*="display: flex; flex-direction: column"] > :first-child:not([style*="sticky"]) .notion-record-icon {
    margin-top: 8px !important;
    margin-right: 8px !important;
    float: left;
}

.notion-scroller[style*="display: flex; flex-direction: column"] > :first-child:not([style*="sticky"]) .notion-page-controls {
  position:absolute !important;
  top: -5px;
}


/* Emoji icon */
.notion-scroller[style*="display: flex; flex-direction: column"] > :first-child:not([style*="sticky"]) .notion-record-icon [style*="font-size: 78px"] {
    font-size: 38px !important;
}


/* Remove space on top of the page when no icon or cover is set  */
.notion-page-controls[style*="margin-top: 80px"] {
    margin-top: 8px !important;
}
```

**Comment by l782993610** [comment]
```css

/* Smaller page icons */

/* Place icon relative to the title container */
.notion-scroller[style*="display: flex; flex-direction: column"] > :first-child > :first-child {
    padding-top: 30px;
    position: relative;
}

/* Set icon size */
.notion-scroller[style*="display: flex; flex-direction: column"] > :first-child .notion-record-icon {
    width: 38px !important;
    height: 38px !important;
}

.notion-scroller[style*="display: flex; flex-direction: column"] > :first-child .notion-record-icon * {
    width: 100% !important;
    height: 100% !important;
}

/* Icon placement */
.notion-scroller[style*="display: flex; flex-direction: column"] > :first-child .notion-record-icon {
    margin-top: 8px !important;
    margin-right: 8px !important;
    float: left;
}

.notion-scroller[style*="display: flex; flex-direction: column"] > :first-child .notion-page-controls {
  position:absolute !important;
  top: -5px;
}

/* Emoji icon */
.notion-scroller[style*="display: flex; flex-direction: column"] > :first-child .notion-record-icon [style*="font-size: 78px"] {
    font-size: 38px !important;
}


/* Remove space on top of the page when no icon or cover is set  */
.notion-page-controls[style*="margin-top: 80px"] {
    margin-top: 8px !important;
}

.notion-page-controls[style*="margin-top: 32px"] {
    margin-top: 8px !important;
}
```

**Comment by l782993610** [comment]
If you have ever change the padding of page，you must add
```css
/* Repair padding of title */
.notion-scroller.horizontal.vertical[style*="display: flex; flex-direction: column"] > :first-child > :first-child[style*="width: 900px"] {
  padding-left: 50px !important
}
```

**Comment by l782993610** [comment]
At version 2.11.23.10.3.1

```css
/* Smaller page icons */

/* Place icon relative to the title container */
.notion-scroller[style*="display: flex; flex-direction: column"] > :nth-child(2) > :first-child:not([style *= "display: flex"]) {
    padding-top: 30px;
    position: relative;
}

/* Set icon size */
.notion-scroller[style*="display: flex; flex-direction: column"] > :nth-child(2) > :first-child:not([style *= "display: flex"]) .notion-record-icon {
    width: 38px !important;
    height: 38px !important;
}

.notion-scroller[style*="display: flex; flex-direction: column"] > :nth-child(2) > :first-child:not([style *= "display: flex"]) .notion-record-icon * {
    width: 100% !important;
    height: 100% !important;
}

/* Icon placement */
.notion-scroller[style*="display: flex; flex-direction: column"] > :nth-child(2) > :first-child:not([style *= "display: flex"]) .notion-record-icon {
    margin-top: 8px !important;
    margin-right: 8px !important;
    float: left;
}

.notion-scroller[style*="display: flex; flex-direction: column"] > :nth-child(2) > :first-child:not([style *= "display: flex"]) .notion-page-controls {
  position:absolute !important;
  top: -5px;
}

/* Emoji icon */
.notion-scroller[style*="display: flex; flex-direction: column"] > :nth-child(2) > :first-child:not([style *= "display: flex"]) .notion-record-icon [style*="font-size: 78px"] {
    font-size: 38px !important;
}


/* Remove space on top of the page when no icon or cover is set  */
.notion-page-controls[style*="margin-top: 80px"] {
    margin-top: 8px !important;
}

.notion-page-controls[style*="margin-top: 32px"] {
    margin-top: 8px !important;
}

```

Also, if you have ever change the left padding of page, you need extra css stylesheet.Do remember to replace the '50px' bellow by the padding you set.
```css
/* Repair padding of title */
.notion-scroller.horizontal.vertical[style*="display: flex; flex-direction: column"] > :nth-child(2) > :first-child:not([style *= "display: flex"]) > :first-child > :first-child{
  padding-left: 50px !important
}
```
